import "@/styles/Home.scss";
import backgroundVideo from "@/resources/videos/wavy_video_background.mp4";
import arrow from "@/resources/images/arrow.svg";
import lines from "@/resources/images/lines.svg";

import React from "react";

import ImageList from "@mui/material/ImageList";
import ImageListItem from "@mui/material/ImageListItem";

import PeopleList from "@/components/PeopleList";

import teamMembers from "@/resources/data/team-members.js";

import {
  workshopImages,
  hackathonImages,
  devchampsImages,
} from "@/resources/data/homepage-mission-images.js";

function MissionImageList({ imagesData }) {
  return (
    <ImageList
      sx={{ width: 500, height: 250 }}
      variant="quilted"
      cols={4}
      rowHeight={121}
    >
      {imagesData.map((item) => (
        <ImageListItem
          key={item.img}
          cols={item.cols || 1}
          rows={item.rows || 1}
        >
          <img
            src={item.img}
            alt={item.title}
            loading="lazy"
            style={{ cursor: "pointer" }}
            onClick={() => {
              window.open(item.img, "_blank");
            }}
          />
        </ImageListItem>
      ))}
    </ImageList>
  );
}

function Home() {
  return (
    <div className="home-container">
      <h1 className="welcome-text">WELCOME TO .DEVCLUB</h1>
      <video
        className="home-video"
        width="100%"
        height="100%"
        autoPlay
        loop
        muted
      >
        <source type="video/mp4" src={backgroundVideo} />
      </video>

      <img className="arrow-homepage" src={arrow} alt="" />
      <div className="white-background">
        <div className="info">
          <div className="aboutAndText">
            <h1 className="about-us">about us</h1>
            <h1 className="team-text">
              team that will give you the best university development
              experience.
            </h1>
          </div>
          <h1 className="description-home">
            We help students achieve their coding goals, and they help us
            accomplish our mission. They help us become technology leaders of
            tomorrow. They make us proud, like you. That's why we invite you to
            join us in celebrating the Top 10 young coders at UofM. Watch us
            celebrate the top young coders at UofM. (Text generated by an AI)
          </h1>
          <img className="lines-homepage" src={lines} alt="" />
        </div>

        <div className="title-container">
          <h1 className="title-content">WHAT WE DO</h1>
        </div>

        <br />
        <br />

        <div className="missions-container">
          <div className="mission-container">
            <div className="mission-text-container">
              <span className="mission-heading">Workshops</span>
              <p className="mission-content">
                Yaknow we have a workshop for you to learn how to code. We have
                workshops for you to learn how to code. We have workshops for
                you to learn how to code. We have workshops for you to learn how
                to code. We have workshops for you to learn how to code. We have
              </p>
            </div>
            <div className="mission-images-container">
              <MissionImageList imagesData={workshopImages} />
            </div>
          </div>

          <div className="mission-container">
            <div className="mission-text-container">
              <span className="mission-heading">Yearly Hackathon</span>
              <p className="mission-content">
                Yaknow we have a workshop for you to learn how to code. We have
                workshops for you to learn how to code. We have workshops for
                you to learn how to code. We have workshops for you to learn how
                to code. We have workshops for you to learn how to code. We have
              </p>
            </div>
            <div className="mission-images-container">
              <MissionImageList imagesData={hackathonImages} />
            </div>
          </div>

          <div className="mission-container">
            <div className="mission-text-container">
              <span className="mission-heading">.devChamps</span>
              <p className="mission-content">
                Yaknow we have a workshop for you to learn how to code. We have
                workshops for you to learn how to code. We have workshops for
                you to learn how to code. We have workshops for you to learn how
                to code. We have workshops for you to learn how to code. We have
              </p>
            </div>
            <div className="mission-images-container">
              <MissionImageList imagesData={devchampsImages} />
            </div>
          </div>
        </div>

        <div className="title-container">
          <h1 className="title-content">OUR TEAM</h1>
        </div>

        <PeopleList peopleData={teamMembers} />
      </div>
      <footer className="footer">
        <h2 className="footer-text">website under construction</h2>
      </footer>
    </div>
  );
}

export default Home;
