name: Build
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "[20.x]"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build && echo ".devclub.ca" > ./build/CNAME
